# Generated by Django 5.2 on 2025-08-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "Product Gallery",
                "verbose_name_plural": "Product Galleries",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("XS", "Extra Small"),
                    ("SM", "Small"),
                    ("LG", "Large"),
                    ("XXL", "Extra Extra Large"),
                ],
                default="SM",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "Color"), ("size", "Size")], max_length=100
            ),
        ),
    ]
